apiVersion: v1
kind: Service
metadata:
  name: {{ include "vcbrain.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "vcbrain.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    - port: {{ .Values.service.metricsPort }}
      targetPort: 9090
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: {{ include "vcbrain.name" . }}
